--创建临时表空间
CREATE TEMPORARY TABLESPACE VIDEOANALY_TEMP
TEMPFILE 'D:\app\Administrator\oradata\orcl\VIDEOANALY_TEMP.DBF'
SIZE 32M
AUTOEXTEND ON
NEXT 32M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL;


--创建数据表空间
CREATE TABLESPACE VIDEOANALY_DATA
LOGGING
DATAFILE 'D:\app\Administrator\oradata\orcl\VIDEOANALY_DATA.DBF'
SIZE 32M
AUTOEXTEND ON
NEXT 32M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL;

--创建用户，且指定表空间
CREATE USER VIDEOANALY IDENTIFIED BY "12qwaszxQq"

         ACCOUNT UNLOCK

         DEFAULT TABLESPACE VIDEOANALY_DATA

         TEMPORARY TABLESPACE VIDEOANALY_TEMP;


--用户授权
grant connect,dba to VIDEOANALY;  
grant select any table to VIDEOANALY ;
grant insert any table to VIDEOANALY ;
grant update any table to VIDEOANALY ;
grant delete any table to VIDEOANALY ;